# Generated by Django 4.2.5 on 2023-11-13 17:30

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ad')),
                ('price', models.PositiveIntegerField()),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('image_home', models.ImageField(upload_to='room_images/home/')),
                ('image_detail_1', models.ImageField(upload_to='room_images/detail/')),
                ('image_detail_2', models.ImageField(upload_to='room_images/detail/')),
                ('image_detail_3', models.ImageField(upload_to='room_images/detail/')),
                ('description', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='room_type', unique=True)),
            ],
            options={
                'verbose_name': 'Oda',
                'verbose_name_plural': 'Odalar',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(verbose_name='Giriş Tarihi')),
                ('checkout_date', models.DateField(verbose_name='Çıkış Tarihi')),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otel.room', verbose_name='Oda')),
            ],
            options={
                'verbose_name': 'Rezervasyon',
                'verbose_name_plural': 'Rezervasyonlar',
            },
        ),
    ]
