# Generated by Django 4.2.5 on 2023-10-24 09:45

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('tek', 'Tek Aile'), ('çift_aile', 'Çift Aile'), ('suit', 'Süit'), ('standart', 'Standart'), ('deluxe', 'Deluxe')], max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('image_home', models.ImageField(upload_to='room_images/home/')),
                ('image_detail_1', models.ImageField(upload_to='room_images/detail/')),
                ('image_detail_2', models.ImageField(upload_to='room_images/detail/')),
                ('image_detail_3', models.ImageField(upload_to='room_images/detail/')),
                ('description', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='room_type', unique=True)),
            ],
        ),
    ]
