# Generated by Django 4.2.5 on 2023-10-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('tek_kisilik', 'Tek Kişilik'), ('çift_aile', 'Çift Kişilik'), ('suit', 'Süit'), ('standart', 'Standart'), ('deluxe', 'Deluxe')], max_length=100),
        ),
    ]
