# Generated by Django 4.2.5 on 2023-11-13 17:41

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='room_name', unique=True),
        ),
    ]
